# Generated by Django 2.1.8 on 2019-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
